baseURL = '//faustozamparelli.com/blog'
publishDir = 'public/blog'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'github-style'
[markup.goldmark.renderer]
  unsafe = true

[params]
  author = 'Fausto Zamparelli'
