baseURL = "https://faustozamparelliblog.vercel.app/blog"
publishDir = 'public/blog'
languageCode = 'en-us'
title = 'faustozamparelli'
theme = 'github-style'
[markup.goldmark.renderer]
  unsafe = true
[params]
  author = 'fast'
  github = 'faustozamparelli'
  avatar = 'https://avatars.githubusercontent.com/u/105665123?v=4'
  location = 'Rome'
  userStatusEmoji = '😁'
  description = 'WAKE UP, NEO... YOU ARE NO MORE ON GITHUB'
  headerIcon = 'https://github.com/user-attachments/assets/c764da3e-4882-496b-956d-916913674828'
  url = 'https://www.youtube.com/watch?v=yM1ajPpGP7g'
  email = 'fausto.zamparelli@gmail.com'
  favicon = '/static/favicon.png'

[services]
  [services.googleAnalytics]
    ID = 'G-MZ2X3WCL72'
