baseURL = 'https://faustozamparelli.com/'
realtiveURLs = true
uglyURLs = true 
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'github-style'
[markup.goldmark.renderer]
  unsafe = true

[params]
  author = 'Fausto Zamparelli'
  description = 'You are no more on my Github... Wake up!'
